--DROPPING REDUNDANT TABLES

DROP TABLE IF EXISTS ATTENDENCE;
DROP TABLE IF EXISTS CLASSVENUE;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS STUDENT;

--DEFINING SCHEMA

CREATE TABLE STUDENT
(
	ROLLNUM VARCHAR(40),
	NAME_ VARCHAR(40) NOT NULL,
	GENDER VARCHAR(40) NOT NULL,
	PHONENUMBER VARCHAR(40)
);

CREATE TABLE TEACHER
(
	ID INT,
	NAME_ VARCHAR(40),
	DESIGNATION VARCHAR(40) NOT NULL,
	DEPARTMENT VARCHAR(40) NOT NULL
);

CREATE TABLE CLASSVENUE
(
	ID_ INT,
	BUILDING VARCHAR(40) NOT NULL,
	ROOMNUM INT NOT NULL,
	TEACHER_NAME VARCHAR(40) NOT NULL,
	TEACHER_ID INT NOT NULL
);

CREATE TABLE ATTENDENCE
(
	ROLLNUM VARCHAR(40),
	DATE_ DATE NOT NULL,
	STATUS_ VARCHAR(1) NOT NULL,
	CLASSVENUE INT NOT NULL
);


--HARDCODE/INSERTED VALUES THROUGH INSERT FUNCTION

INSERT INTO STUDENT
VALUES ('L191162', 'ABDULLAH NAZIR', 'MALE', '0333-3333333');
INSERT INTO STUDENT
VALUES ('L194124', 'RAFIA AHMED', 'FEMALE', '0333-3456789');
INSERT INTO STUDENT
VALUES ('L194125', 'BASIT JUNAID', 'MALE', '0345-3243567');

INSERT INTO TEACHER
VALUES (1, 'RAIDA MUNIR', 'LAB INSTRUCTOR', 'COMPUTER SCI.');
INSERT INTO TEACHER
VALUES (2, 'HARIS BIN REHAN', 'LECTURER', 'CIVIL ENGG.');
INSERT INTO TEACHER
VALUES (3, 'SANA FATIMA', 'PROFESSOR', 'ELECTICAL ENGG.');

INSERT INTO CLASSVENUE
VALUES (1, 'COMPUTER SCI.', 2, 'HARIS BIN REHAN', 2);
INSERT INTO CLASSVENUE
VALUES (2, 'CIVIL', 7, 'RAIDA MUNIR', 1);

INSERT INTO ATTENDENCE
VALUES ('L191162', '2023-02-22', 'P', 2);
INSERT INTO ATTENDENCE
VALUES ('L194124', '2023-02-23', 'A', 1);
INSERT INTO ATTENDENCE
VALUES ('L194125', '2023-03-04', 'P', 2);


--ADDING PK CONTRAINTS

ALTER TABLE STUDENT
ADD CONSTRAINT PK_constraint_student
PRIMARY KEY (ROLLNUM);

ALTER TABLE TEACHER
ADD CONSTRAINT PK_constraint_teacher
PRIMARY KEY (ID, NAME_);

ALTER TABLE ATTENDENCE
ADD CONSTRAINT PK_constraint_attendence
PRIMARY KEY (ROLLNUM);

ALTER TABLE CLASSVENUE
ADD CONSTRAINT PK_constraint_classvenue
PRIMARY KEY (ID_);



--ADDING FK CONTRAINTS

ALTER TABLE CLASSVENUE
ADD CONSTRAINT FK_constraint_classvenue
FOREIGN KEY (TEACHER_ID, TEACHER_NAME)
REFERENCES TEACHER (ID, NAME_)
ON DELETE RESTRICT
ON UPDATE RESTRICT;

ALTER TABLE ATTENDENCE
ADD CONSTRAINT FK_constraint_attendence
FOREIGN KEY (CLASSVENUE)
REFERENCES CLASSVENUE (ID_)
ON DELETE RESTRICT
ON UPDATE RESTRICT;


--ADDING WARNING COUNT, DROPPING PHONE-NUMBER

ALTER TABLE STUDENT
DROP COLUMN PHONENUMBER;

ALTER TABLE STUDENT
ADD WARNING_COUNT INT;


--ADDING BASIC CHECKS AND CONSTRAINTS

ALTER TABLE TEACHER
ADD CONSTRAINT unique_name_constraint
UNIQUE (NAME_);

ALTER TABLE STUDENT
ADD CONSTRAINT gender_check_constraint
CHECK (STUDENT.GENDER='MALE' OR STUDENT.GENDER='FEMALE');

ALTER TABLE ATTENDENCE
ADD CONSTRAINT attendence_check_constraint
CHECK (ATTENDENCE.STATUS_='P' OR ATTENDENCE.STATUS_='A');

--TESTING QUERIES

-- VALID QUERY BUT LOGICAL ERROR SINCE THE 'WARNING_COUNT' IS 'FLOAT' AND STORED IN 'INT' 
INSERT INTO STUDENT
VALUES ('L192334', 'SHAHID IQBAL', 'MALE', 3.2);

-- INVALID QUERY BECAUSE, ID --> 4 IS NOT DEFINED IN TEACHER TABLE
-- IT CAN CORRECTED BY INSERTING A TEACHER WITH ID --> 4 AND NAME --> 'ALI' 
INSERT INTO CLASSVENUE
VALUES (3, 'CS', 5, 'ALI', 4);

-- COMPLETELY VALID QUERIES
UPDATE TEACHER
SET NAME_='DR. SANA FATIMA'
WHERE NAME_='SANA FATIMA';

DELETE FROM STUDENT
WHERE ROLLNUM = 'L192334';

DELETE FROM STUDENT
WHERE ROLLNUM = 'L194125';

DELETE FROM ATTENDENCE
WHERE ROLLNUM = 'L194124' AND STATUS_='A';

--SHOWING TABLES 

SELECT * FROM STUDENT;
SELECT * FROM ATTENDENCE;
SELECT * FROM CLASSVENUE;
SELECT * FROM TEACHER;
